import type { Metadata } from 'next'
import './globals.css'
import { MDXViewerProvider } from 'mdx-craft'
import { Fira_Mono, Poppins } from 'next/font/google'
import { ThemeProvider } from './ThemeProvider'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
  weight: ['300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
})

const firaMono = Fira_Mono({
  subsets: ['latin'],
  variable: '--font-fira-mono',
  display: 'swap',
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${firaMono.variable} ${poppins.variable} font-sans antialiased`}>
        <ThemeProvider defaultTheme="dark">
          {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
          <MDXViewerProvider>{children as any}</MDXViewerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
