import { type JSX } from 'react'
import type { Metadata } from 'next'
import { Poppins, Fira_Mono } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { MDXViewerProvider } from '@sl/mdx-craft'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
})

const firaMono = Fira_Mono({
  variable: '--font-fira-mono',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(poppins.className, firaMono.variable, 'antialiased')}>
        <ThemeProvider
          defaultTheme="dark"
          enableSystem={false}
          attribute="class"
          disableTransitionOnChange
        >
          <MDXViewerProvider>{children}</MDXViewerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
