blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/yourusername/mdx-craft/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://mdx-craft-docs.vercel.app
    about: Check out our documentation for guides and API reference